# Generated by Django 5.0.2 on 2025-02-13 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0024_delete_payment_esewatransaction_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='esewatransaction',
            old_name='user',
            new_name='CustomUser',
        ),
    ]
