# Generated by Django 5.0.2 on 2025-02-13 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0025_rename_user_esewatransaction_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='esewatransaction',
            old_name='CustomUser',
            new_name='user',
        ),
    ]
